# Generated by Django 5.0.6 on 2024-07-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_alter_email_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
